[project]
name = "multi-agent-systems"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "agno>=3.0.9",
    "google-genai>=2.22.0",
    "openai>=3.10.0",
    "sqlalchemy>=2.0.52",
    "ddgs>=9.16.0",
    "redis>=8.1.0",
    "qdrant_client>=1.19.0",
    "fastembed>=0.8.0",
    "tavily-python>=0.8.1",
    "yfinance>=1.7.0",
    "ollama>=0.6.2",
    "pypdf>=6.18.0",
    "mcp>=2.2.0",
    "fastmcp>=4.0.3"
]